import type { Metadata } from 'next';
import './globals.css';
import ReactQueryProvider from './ReactQueryProvider';
import * as stylex from '@stylexjs/stylex';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body {...stylex.props(styles.body)}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}

const styles = stylex.create({
  body: {
    boxSizing: 'border-box',
    background: 'black',
  },
});
